language: generic
sudo: required
services:
  - docker


before_install:
  - docker build -t radhekrishna/docker-react -f dockerfile.dev .


scripts:
  - docker run -e CI=true radheskrishna/docker-react npm run test